### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yokoyamamio** [CCYellowStar2/nonebot-plugin-aising#2]
```
root@ECS1033:~/qb2/qb/NeuCoSVC-2# python3 app_colab.py
Traceback (most recent call last):
  File "/root/qb2/qb/NeuCoSVC-2/app_colab.py", line 78, in <module>
    pre_fun_hp2 = func(
  File "/root/qb2/qb/NeuCoSVC-2/uvr5/vr.py", line 31, in __init__
    cpk = torch.load(model_path, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by CCYellowStar2** [comment]
是怎么出现的

**Comment by CCYellowStar2** [comment]
可能是你git clone的时候模型没有完全下载下来，检查下NeuCoSVC-2\uvr5\uvr_model目录里的模型是否下载完整
![image](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/149048350/90e19674-6e2f-49e0-89f4-46a6f59f2c5c)

**Comment by yokoyamamio** [comment]
好的，感谢，等我有时间看看





发自我的iPhone


------------------ Original ------------------
From: CCYellowStar2 ***@***.***&gt;
Date: Fri,Jun 7,2024 3:41 PM
To: CCYellowStar2/nonebot-plugin-aising ***@***.***&gt;
Cc: yokoyamamio ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [CCYellowStar2/nonebot-plugin-aising] bug (Issue #2)





 
可能是你git clone的时候模型没有完全下载下来，检查下NeuCoSVC-2\uvr5\uvr_model目录里的模型是否下载完整
 image.png (view on web)

**Comment by CCYellowStar2** [comment]
现在更新了，这两个文件没了，你重新装下后端

**Comment by yokoyamamio** [comment]
非常感谢您！最近没什么时间来管bot！非常感谢您的帮助！也为我这段时间没回复在这里跟您说一声抱歉！
