### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'output_svc/NeuCoSVCv2.wav' = =、

### ISSUE THREAD

**Issue by mjzxssx** [CCYellowStar2/nonebot-plugin-aising#7]
100%|█████████████████████████████████████████████| 62/62 [07:38<00:00,  7.39s/it]
/remote/me/NeuCoSVC-2/uvr5/lib/lib_v5/spec_utils.py:396: FutureWarning: Pass orig_sr=7350, target_sr=7350 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  wave = librosa.resample(
/remote/me/NeuCoSVC-2/uvr5/lib/lib_v5/spec_utils.py:422: FutureWarning: Pass orig_sr=7350, target_sr=14700 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  wave = librosa.core.resample(wave2, bp["sr"], sr, res_type="scipy")
/remote/me/NeuCoSVC-2/uvr5/lib/lib_v5/spec_utils.py:422: FutureWarning: Pass orig_sr=14700, target_sr=44100 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  wave = librosa.core.resample(wave2, bp["sr"], sr, res_type="scipy")
sh: 1: pythonpython.exe: not found
Traceback (most recent call last):
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, args)
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/gradio/utils.py", line 805, in wrapper
    response = f(args, **kwargs)
  File "/remote/me/NeuCoSVC-2/app_colab.py", line 309, in convert
    audio_vocal = AudioSegment.from_file("output_svc/NeuCoSVCv2.wav", format="wav")
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/pydub/audio_segment.py", line 651, in from_file
    file, close_file = fdor_path_or_tempfile(file, 'rb', tempfile=False)
  File "/remote/me/NeuCoSVC-2/venv/lib/python3.10/site-packages/pydub/utils.py", line 60, in fdor_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'output_svc/NeuCoSVCv2.wav'

**Comment by mjzxssx** [comment]
<img width="210" alt="image" src="https://github.com/user-attachments/assets/86fe3ba9-7827-4b5b-b721-8db4acc6ed22">
实际上并没有生成NeuCoSVCv2.wav

**Comment by mjzxssx** [comment]
环境 linux mint X64

**Comment by mjzxssx** [comment]
定位后发现调用的是python.exe，修改app.py中的代码进行尝试
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/719876e0-6650-4ab2-aa02-20689bfcd87e">

**Comment by mjzxssx** [comment]
已解决，遇到permission denied问题，执行/remote/me/NeuCoSVC-2$ sudo chmod 777 REAPER/build/reaper
